/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.seuprojeto.classes;

import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laura
 */
public class consultaDados extends javax.swing.JFrame {
    private final JTable table; // Tabela onde os dados serão exibidos
    private final DefaultTableModel model; // Modelo de tabela
    

    public consultaDados() {
        initComponents();
        setTitle("Consulta de Dados");
        setLocationRelativeTo(null);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {},
    new String [] {
        "ID", "Nome", "Idade", "Data de Nascimento"
    }
));


        // Criação da tabela com colunas que você deseja exibir
        model = new DefaultTableModel(new Object[]{"ID", "Nome", "Idade", "Data de Nascimento"}, 0);
        table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane); // Adiciona a tabela à janela
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }

    // Método para carregar dados do banco de dados
public void loadData() {
    Connection conn = dataBaseConnection.connect();
    if (conn != null) {
        System.out.println("✅ Conectado ao banco!");
        try {
            String query = "SELECT * FROM pessoas"; // Substitua pelo nome correto da sua tabela
            try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(query)) {

                // Obtém o modelo da tabela existente no design
                DefaultTableModel modell = (DefaultTableModel) jTable1.getModel();
                modell.setRowCount(0); // Limpa a tabela antes de adicionar os dados

                // Adiciona os dados do banco na tabela
                while (rs.next()) {
                    int id = rs.getInt("id");
                    String nome = rs.getString("nome");
                    int idade = rs.getInt("idade");
                    String dataNascimento = rs.getString("data_nascimento"); // Nome correto da coluna no banco
                    modell.addRow(new Object[]{id, nome, idade, dataNascimento});
                }

            }
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Erro na conexão com o banco de dados.");
    }
}

    /**
     * Creates new form consultaDados
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    SwingUtilities.invokeLater(() -> {
        consultaDados janela = new consultaDados();
        janela.setVisible(true);
        janela.loadData(); // Agora a jTable1 será preenchida com os dados
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
